F31: ["Male"]
F21000: ["British", "Irish", "Any other white background"]
F1717: ["Very fair", "Fair", "Light olive"]
F1647: ["England", "Wales", "Scotland", "Northern Ireland", "Republic of Ireland"]
F189: 0.8
F34: 65
F21001: 30